service: pws-api
org: eriktim

frameworkVersion: '2'

provider:
  name: aws
  runtime: java11
  stage: dev
  region: eu-west-1
  lambdaHashingVersion: 20201221

package:
  artifact: target/scala-2.13/root-assembly-0.1.0-SNAPSHOT.jar

functions:
  logMeasurement:
    handler: io.timmers.pws.function.Function::logMeasurement
    events:
      - httpApi:
          path: /log
          method: get

resources:
  Resources:
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Comment: CloudFront distribution to serve logging over HTTP
          DefaultCacheBehavior:
            TargetOriginId: PwsLog
            ViewerProtocolPolicy: 'allow-all'
            DefaultTTL: 0
            MinTTL: 0
            MaxTTL: 0
            ForwardedValues:
              QueryString: true
          PriceClass: PriceClass_100
          Enabled: true
          Origins:
            - Id: PwsLog
              DomainName:
                Fn::Join:
                  - "."
                  - - Ref: HttpApi
                    - execute-api
                    - Ref: AWS::Region
                    - amazonaws.com
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only
                OriginSSLProtocols:
                  - TLSv1.2